/**
 * CODE-ALTERATION-REPORT.md Generator
 *
 * Generates a detailed report of every code change CodeSentry makes,
 * including reasoning, affected files, before/after diffs, and model
 * verification results.
 */
const fs   = require('node:fs');
const path = require('node:path');

/**
 * @typedef {Object} AlterationEntry
 * @property {string} file       – relative file path
 * @property {number} line       – primary line affected
 * @property {string} rule       – the rule that triggered the fix
 * @property {string} severity   – HIGH / MEDIUM / LOW
 * @property {string} problem    – description of the problem found
 * @property {string} reasoning  – why this fix was chosen
 * @property {string} before     – original code snippet (context)
 * @property {string} after      – replacement code snippet
 * @property {string} strategy   – exact / normalised / fuzzy / AI
 * @property {string} model      – which AI model suggested/verified it (or 'deterministic')
 * @property {boolean} verified  – whether a second model verified the fix
 * @property {string} status     – APPLIED | SKIPPED | FAILED
 */

class AlterationReporter {
  constructor(projectPathOrOptions = {}) {
    if (typeof projectPathOrOptions === 'string') {
      this.projectPath = projectPathOrOptions;
      this.options = {};
    } else {
      this.options = projectPathOrOptions || {};
      this.projectPath = this.options.projectPath || process.cwd();
    }
    /** @type {AlterationEntry[]} */
    this.entries     = [];
    this.startTime   = new Date();
    this.scanMeta    = {
      model: this.options.model,
      provider: this.options.provider,
    };
  }

  /**
   * Record a single code alteration.
   * @param {AlterationEntry} entry
   */
  addEntry(entry) {
    const finding = entry.finding || {};
    const fix = entry.fix || {};
    const status = (entry.status || 'applied').toUpperCase();

    this.entries.push({
      timestamp: new Date().toISOString(),
      file: entry.file || finding.file || 'unknown',
      line: entry.line || finding.line || 1,
      rule: entry.rule || finding.rule || finding.category || 'rule',
      severity: entry.severity || finding.severity || 'MEDIUM',
      problem: entry.problem || finding.message || 'Issue detected in static analysis',
      reasoning: entry.reasoning || fix.explanation || entry.reason || 'Applied automated code repair',
      before: entry.before !== undefined ? entry.before : (fix.oldSnippet || ''),
      after: entry.after !== undefined ? entry.after : (fix.newSnippet || ''),
      strategy: entry.strategy || entry.method || 'deterministic',
      model: entry.model || entry.modelUsed || this.scanMeta.model || (entry.method === 'deterministic' ? 'deterministic rule' : 'AI'),
      verified: Boolean(entry.verified || entry.status === 'applied'),
      status,
    });
  }

  /**
   * Attach scan metadata (model used, provider, score, etc.)
   */
  setScanMeta(meta) {
    this.scanMeta = { ...this.scanMeta, ...meta };
  }

  /**
   * Generate the markdown report.
   * @returns {string} markdown content
   */
  generateMarkdown() {
    const now   = new Date();
    const dur   = ((now - this.startTime) / 1000).toFixed(1);
    const total = this.entries.length;
    const applied = this.entries.filter(e => e.status === 'APPLIED').length;
    const skipped = this.entries.filter(e => e.status === 'SKIPPED').length;
    const failed  = this.entries.filter(e => e.status === 'FAILED').length;

    let md = '';
    md += `# 🔧 CODE-ALTERATION-REPORT\n\n`;
    md += `> Auto-generated by **CodeSentry** on ${now.toISOString()}\n\n`;
    md += `## Summary\n\n`;
    md += `| Metric | Value |\n`;
    md += `|--------|-------|\n`;
    md += `| Project | \`${this.projectPath}\` |\n`;
    md += `| Duration | ${dur}s |\n`;
    md += `| Total Alterations | ${total} |\n`;
    md += `| ✅ Applied | ${applied} |\n`;
    md += `| ⏭️ Skipped | ${skipped} |\n`;
    md += `| ❌ Failed | ${failed} |\n`;
    if (this.scanMeta.model) {
      md += `| AI Model | \`${this.scanMeta.model}\` |\n`;
    }
    if (this.scanMeta.provider) {
      md += `| Provider | ${this.scanMeta.provider} |\n`;
    }
    if (this.scanMeta.score !== undefined) {
      md += `| Health Score | ${this.scanMeta.score}/100 |\n`;
    }
    md += `\n`;

    // ── Per-file grouped entries ──
    const byFile = {};
    for (const entry of this.entries) {
      if (!byFile[entry.file]) byFile[entry.file] = [];
      byFile[entry.file].push(entry);
    }

    md += `## Alterations by File\n\n`;

    for (const [file, entries] of Object.entries(byFile)) {
      md += `### 📄 \`${file}\`\n\n`;

      for (const entry of entries) {
        const icon = entry.status === 'APPLIED' ? '✅' : entry.status === 'SKIPPED' ? '⏭️' : '❌';
        md += `#### ${icon} Line ${entry.line} — \`${entry.rule}\` (${entry.severity})\n\n`;
        md += `**Problem:** ${entry.problem}\n\n`;
        md += `**Reasoning:** ${entry.reasoning}\n\n`;
        md += `**Strategy:** ${entry.strategy}`;
        if (entry.model) md += ` | **Model:** \`${entry.model}\``;
        if (entry.verified) md += ` | ✅ Verified`;
        md += `\n\n`;

        if (entry.before || entry.after) {
          md += `<details><summary>View diff</summary>\n\n`;
          if (entry.before) {
            md += `**Before:**\n\`\`\`\n${entry.before}\n\`\`\`\n\n`;
          }
          if (entry.after) {
            md += `**After:**\n\`\`\`\n${entry.after}\n\`\`\`\n\n`;
          }
          md += `</details>\n\n`;
        }

        md += `---\n\n`;
      }
    }

    // ── Verification Summary ──
    const verified   = this.entries.filter(e => e.verified).length;
    const unverified = applied - verified;
    md += `## Verification Summary\n\n`;
    md += `- **Verified by AI model:** ${verified} alterations\n`;
    md += `- **Deterministic (no AI needed):** ${unverified} alterations\n`;
    md += `- **Skipped (risky / no confident fix):** ${skipped} alterations\n\n`;

    md += `---\n*Report generated by CodeSentry automated repair engine.*\n`;

    return md;
  }

  /**
   * Write the report to disk.
   * @param {string} [outputDir] – defaults to project root
   * @returns {string} path to written file
   */
  writeReport(outputDir) {
    const dir = outputDir || this.projectPath;
    const reportPath = path.join(dir, 'CODE-ALTERATION-REPORT.md');
    const content = this.generateMarkdown();
    fs.writeFileSync(reportPath, content, 'utf-8');
    return reportPath;
  }
}

module.exports = { AlterationReporter };
