'use strict';

/**
 * CodeSentry AI Security Advisor & Hardening Engine
 *
 * All security suggestions are dynamically generated by AI models (OpenRouter)
 * based on the specific architecture, manifests, and languages of the clean codebase.
 */

const fs = require('node:fs');
const path = require('node:path');
const https = require('node:https');
const theme = require('./theme');

const AI_SECURITY_SYSTEM_PROMPT = [
  'You are CodeSentry AI, a Principal Application Security Architect and penetration tester.',
  'The user scanned their codebase and it is confirmed clean with 0 known vulnerabilities or bugs.',
  'Your job is to analyze the project context, dependencies, and frameworks to provide high-impact,',
  'defense-in-depth security hardening recommendations tailored specifically to this codebase.',
  'You MUST respond with valid JSON only — no markdown fences, no conversational prose outside JSON.',
  'The JSON object must have this exact structure:',
  '{',
  '  "summary": "Overall assessment of the project defense-in-depth posture",',
  '  "suggestions": [',
  '    {',
  '      "title": "Concise title of the recommendation",',
  '      "category": "headers | auth | rate-limiting | supply-chain | validation | secrets",',
  '      "priority": "HIGH | MEDIUM | LOW",',
  '      "explanation": "Why this specific project needs this hardening measure",',
  '      "suggestedFix": "Actionable technical instructions",',
  '      "codeExample": "Production-ready code snippet tailored to their framework"',
  '    }',
  '  ]',
  '}',
].join('\n');

/**
 * Extracts codebase context (manifests, languages, file structure) for AI prompt.
 */
function extractProjectContext(projectPath) {
  const root = path.resolve(projectPath);
  const context = {
    projectName: path.basename(root),
    manifest: null,
    frameworks: [],
    languages: [],
    filesSample: [],
  };

  // Node.js package.json
  const pkgPath = path.join(root, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      context.manifest = {
        name: pkg.name,
        dependencies: Object.keys(pkg.dependencies || {}),
        devDependencies: Object.keys(pkg.devDependencies || {}),
        scripts: pkg.scripts || {},
      };
      context.languages.push('javascript');
      if (context.manifest.devDependencies.some(d => d.includes('typescript')) || fs.existsSync(path.join(root, 'tsconfig.json'))) {
        context.languages.push('typescript');
      }
      if (context.manifest.dependencies.includes('express')) context.frameworks.push('express');
      if (context.manifest.dependencies.includes('fastify')) context.frameworks.push('fastify');
      if (context.manifest.dependencies.includes('next')) context.frameworks.push('next.js');
      if (context.manifest.dependencies.includes('koa')) context.frameworks.push('koa');
    } catch {}
  }

  // Python manifests
  const reqPath = path.join(root, 'requirements.txt');
  if (fs.existsSync(reqPath)) {
    try {
      const reqs = fs.readFileSync(reqPath, 'utf8').split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('#'));
      context.manifest = { pythonRequirements: reqs.slice(0, 30) };
      context.languages.push('python');
      if (reqs.some(r => r.toLowerCase().includes('flask'))) context.frameworks.push('flask');
      if (reqs.some(r => r.toLowerCase().includes('django'))) context.frameworks.push('django');
      if (reqs.some(r => r.toLowerCase().includes('fastapi'))) context.frameworks.push('fastapi');
    } catch {}
  }

  // Sample top-level directory structure
  try {
    const entries = fs.readdirSync(root, { withFileTypes: true });
    context.filesSample = entries
      .filter(e => !e.name.startsWith('.') && e.name !== 'node_modules' && e.name !== '__pycache__')
      .slice(0, 20)
      .map(e => e.isDirectory() ? `${e.name}/` : e.name);
  } catch {}

  return context;
}

/**
 * Queries the active AI Model to generate tailored security suggestions.
 */
async function queryAISecuritySuggestions(projectPath, options = {}) {
  const context = extractProjectContext(projectPath);
  const apiKey = options.apiKey || process.env.OPENROUTER_API_KEY;
  const model = options.model || process.env.OPENROUTER_MODEL || 'poolside/laguna-s-2.1:free';
  const mockMode = options.mockMode !== undefined ? options.mockMode : !apiKey;

  if (mockMode) {
    return generateMockAISuggestions(context, model);
  }

  const prompt = [
    `Project: ${context.projectName}`,
    `Languages: ${context.languages.join(', ') || 'polyglot'}`,
    `Frameworks: ${context.frameworks.join(', ') || 'generic'}`,
    `Structure: ${context.filesSample.join(', ')}`,
    context.manifest ? `Manifest: ${JSON.stringify(context.manifest)}` : '',
    '',
    'Codebase has passed static audit with 0 findings. Provide 3-4 proactive security hardening suggestions.',
  ].join('\n');

  const messages = [
    { role: 'system', content: AI_SECURITY_SYSTEM_PROMPT },
    { role: 'user', content: prompt },
  ];

  const { response, modelUsed } = await callOpenRouterAPIWithFallback(messages, model, apiKey);
  const parsed = parseAIResponse(response);

  return {
    model: modelUsed,
    summary: parsed.summary || 'Proactive security posture assessment generated by AI model.',
    suggestions: parsed.suggestions || [],
  };
}

const ENHANCER_FREE_MODELS = [
  'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
  'nvidia/nemotron-3.5-lightning:free',
  'poolside/laguna-s-2.1:free',
  'cohere/north-mini-code:free',
];

async function callOpenRouterAPIWithFallback(messages, requestedModel, apiKey) {
  const modelsToTry = [];
  if (requestedModel && requestedModel !== 'auto') {
    modelsToTry.push(requestedModel);
  }
  for (const m of ENHANCER_FREE_MODELS) {
    if (!modelsToTry.includes(m)) modelsToTry.push(m);
  }

  let lastError = null;
  for (const m of modelsToTry) {
    try {
      const response = await callOpenRouterAPI(messages, m, apiKey);
      return { response, modelUsed: m };
    } catch (err) {
      lastError = err;
      continue;
    }
  }
  throw lastError || new Error('Failed to query AI model across all fallback models');
}

/**
 * Direct HTTPS call to OpenRouter API (zero npm dependencies).
 */
function callOpenRouterAPI(messages, model, apiKey) {
  return new Promise((resolve, reject) => {
    const postData = JSON.stringify({
      model,
      max_tokens: 1500,
      temperature: 0.3,
      messages,
    });

    const options = {
      hostname: 'openrouter.ai',
      port: 443,
      path: '/api/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'HTTP-Referer': 'https://github.com/codesentry/codesentry',
        'X-Title': 'CodeSentry Security Engine',
        'Content-Length': Buffer.byteLength(postData),
      },
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          if (json.error) {
            reject(new Error(json.error.message || 'OpenRouter API error'));
            return;
          }
          resolve(json);
        } catch (e) {
          reject(new Error(`Failed to parse AI response: ${e.message}`));
        }
      });
    });

    req.on('error', reject);
    req.setTimeout(35000, () => {
      req.destroy(new Error('AI model request timed out'));
    });

    req.write(postData);
    req.end();
  });
}

/**
 * Robust JSON parser for AI model responses (cleans markdown fences and outer wrappers).
 */
function parseAIResponse(apiResponse) {
  const content = apiResponse.choices?.[0]?.message?.content;
  if (!content) return { summary: 'No suggestions generated', suggestions: [] };

  let cleaned = content.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
  const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    try {
      return JSON.parse(jsonMatch[0]);
    } catch {}
  }

  return {
    summary: 'AI Security Hardening Suggestions',
    suggestions: [
      {
        title: 'Architectural Defense-in-Depth',
        category: 'headers',
        priority: 'HIGH',
        explanation: content,
        suggestedFix: 'Implement multi-layered defense controls.',
        codeExample: '',
      },
    ],
  };
}

/**
 * High-fidelity mock AI suggestions for testing and offline development.
 */
function generateMockAISuggestions(context, model) {
  const isPython = context.languages.includes('python');
  const suggestions = isPython
    ? [
        {
          title: 'Implement Security Response Headers & CSP (flask-talisman)',
          category: 'headers',
          priority: 'HIGH',
          explanation: 'Your Python endpoints are free of static vulnerabilities, but require HTTP headers to defend against clickjacking, MIME-sniffing, and Cross-Site Scripting (XSS).',
          suggestedFix: 'Install flask-talisman and wrap your application instance with strict Content Security Policy and HSTS.',
          codeExample: 'from flask import Flask\nfrom flask_talisman import Talisman\n\napp = Flask(__name__)\nTalisman(app, content_security_policy={"default-src": "\'self\'"}, force_https=True)',
        },
        {
          title: 'Add Endpoint Rate Limiting & Brute-Force Defense (slowapi)',
          category: 'rate-limiting',
          priority: 'HIGH',
          explanation: 'Without rate limiting, public authentication routes remain susceptible to credential-stuffing and volumetric denial of service.',
          suggestedFix: 'Add slowapi to rate limit sensitive endpoints to 5 attempts per minute per IP.',
          codeExample: 'from slowapi import Limiter\nfrom slowapi.util import get_remote_address\n\nlimiter = Limiter(key_func=get_remote_address)\n@app.route("/login", methods=["POST"])\n@limiter.limit("5/minute")\ndef login(): ...',
        },
        {
          title: 'Enforce Runtime Schema Validation (Pydantic)',
          category: 'validation',
          priority: 'MEDIUM',
          explanation: 'Type checking at code boundaries prevents malicious payloads and parameter tampering before entering business logic.',
          suggestedFix: 'Define strict Pydantic models with extra="forbid" for all incoming request payloads.',
          codeExample: 'from pydantic import BaseModel, ConfigDict\n\nclass UserPayload(BaseModel):\n    model_config = ConfigDict(extra="forbid")\n    username: str\n    email: str',
        },
      ]
    : [
        {
          title: 'Harden HTTP Security Headers with Helmet & Strict CSP',
          category: 'headers',
          priority: 'HIGH',
          explanation: 'Even with zero source bugs, browsers must be instructed to block MIME sniffing, Clickjacking, and unauthorized inline script execution.',
          suggestedFix: 'Install helmet and configure explicit Content-Security-Policy with frameAncestors: ["\'none\'"].',
          codeExample: "const helmet = require('helmet');\napp.use(helmet({\n  contentSecurityPolicy: {\n    directives: {\n      defaultSrc: [\"'self'\"],\n      objectSrc: [\"'none'\"],\n      frameAncestors: [\"'none'\"],\n    },\n  },\n  hsts: { maxAge: 31536000, includeSubDomains: true },\n}));",
        },
        {
          title: 'Implement API Rate Limiting & DoS Mitigation',
          category: 'rate-limiting',
          priority: 'HIGH',
          explanation: 'Unthrottled public endpoints leave your service vulnerable to volumetric resource exhaustion and automated credential attacks.',
          suggestedFix: 'Add express-rate-limit to enforce a maximum of 100 requests per 15 minutes per IP on API routes.',
          codeExample: "const rateLimit = require('express-rate-limit');\nconst limiter = rateLimit({\n  windowMs: 15 * 60 * 1000,\n  max: 100,\n  standardHeaders: true,\n  legacyHeaders: false,\n});\napp.use('/api/', limiter);",
        },
        {
          title: 'Secure Cookie Flags for Session Tokens',
          category: 'auth',
          priority: 'MEDIUM',
          explanation: 'Ensure authentication tokens cannot be read by injected scripts or transmitted over plaintext channels.',
          suggestedFix: "Always set httpOnly: true, secure: true, and sameSite: 'strict' on cookies.",
          codeExample: "res.cookie('token', sessionToken, {\n  httpOnly: true,\n  secure: process.env.NODE_ENV === 'production',\n  sameSite: 'strict',\n  maxAge: 3600000,\n});",
        },
      ];

  return {
    model: `${model} (Simulated)`,
    summary: 'AI Architectural Security Assessment: Clean codebase verified. Proactive defense-in-depth measures recommended.',
    suggestions,
  };
}

/**
 * Formats AI security suggestion cards for the terminal.
 */
function formatAISuggestionCard(suggestion, index, total, model) {
  const c = theme.colors;
  const priorityBadge = suggestion.priority === 'HIGH'
    ? theme.severityBadge('HIGH')
    : theme.severityBadge('MEDIUM');

  const lines = [
    `${c.cyan('▎ Area:')}        ${priorityBadge} ${c.brightWhite(theme.bold(suggestion.title))}`,
    `${c.cyan('▎ Category:')}    ${theme.categoryBadge(suggestion.category || 'security')}`,
    `${c.cyan('▎ Why it matters:')}`,
    `  ${c.gray(suggestion.explanation)}`,
    '',
    `${c.cyan('▎ AI Recommendation:')}`,
    `  ${c.white(suggestion.suggestedFix)}`,
  ];

  if (suggestion.codeExample) {
    lines.push('');
    lines.push(`${c.cyan('▎ Implementation Blueprint:')}`);
    const codeLines = suggestion.codeExample.split('\n');
    for (const cl of codeLines) {
      lines.push(`  ${c.cyan('│')} ${c.teal(cl)}`);
    }
  }

  return theme.card(lines, {
    title: c.cyan(theme.bold(`AI SECURITY HARDENING [${index + 1}/${total}]`)),
    rightTitle: c.gray(`AI: ${model}`),
    width: 72,
  });
}

/**
 * Exports AI security suggestions to markdown file in project.
 */
function exportAISuggestionsToMarkdown(projectPath, aiResult) {
  const root = path.resolve(projectPath);
  const outPath = path.join(root, 'AI-SECURITY-SUGGESTIONS.md');

  const lines = [
    '# 🤖 AI Proactive Security Hardening Suggestions',
    '',
    `> **Evaluated by AI Model**: \`${aiResult.model}\`  `,
    `> **Audit Status**: Baseline Clean (0 known vulnerabilities or bugs)  `,
    `> **Generated**: ${new Date().toLocaleString()}`,
    '',
    '## Executive Summary',
    '',
    aiResult.summary,
    '',
    '---',
    '',
  ];

  for (let i = 0; i < aiResult.suggestions.length; i++) {
    const s = aiResult.suggestions[i];
    lines.push(`## ${i + 1}. ${s.title}`);
    lines.push('');
    lines.push(`- **Category**: \`${s.category}\``);
    lines.push(`- **Priority**: **${s.priority}**`);
    lines.push('');
    lines.push('### Architectural Rationale');
    lines.push(s.explanation);
    lines.push('');
    lines.push('### Recommended Action');
    lines.push(s.suggestedFix);
    lines.push('');
    if (s.codeExample) {
      lines.push('### Implementation Blueprint');
      lines.push('```javascript');
      lines.push(s.codeExample);
      lines.push('```');
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  return outPath;
}

module.exports = {
  queryAISecuritySuggestions,
  formatAISuggestionCard,
  exportAISuggestionsToMarkdown,
  extractProjectContext,
};
